version: '3'
services:
  brewdb:
    container_name: brewdb
    build: ./brewdb/
    ports:
      - "5432:5432"
  brew_pipe:
    container_name: brew_pipe
    build: ./brew_pipe/
    ports:
      - "8888:8888"
    volumes:
      - ./brew_pipe:/brew_pipe
      - ./brew_data:/brew_data
      - ./brewdb:/brewdb
    tty: true
    environment:
      BREWDB_HOST: localhost
    depends_on:
      - brewdb
  brew-web-ui:
    container_name: brew-web-ui
    build: ./brew-web-ui/
    ports:
      - '3000:3000'
    volumes:
      - ./brew-web-ui:/brew-web-ui
      - /brew-web-ui/node_modules
